<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplikasi Scoring Pencak Silat</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">

</head>
<body class="bg-gradient-to-br from-red-50 to-indigo-100 min-h-screen">

    <input type="hidden" id="pertandingan_id" value="{{ $pertandingan->id ?? 1 }}">
    <input type="hidden" id="user_id" value="{{ $user->id ?? 1 }}">
    <input type="hidden" id="max_jurus" value="{{ $maxJurus ?? 14 }}">
    <input type="hidden" id="match_type" value="{{ $matchType ?? 'tunggal' }}">

    <div class="container mx-auto p-4 max-w-7xl">
        <!-- Header -->
        <div class="bg-white rounded-xl shadow-md p-6 mb-6">
            <div class="flex items-center justify-between">
                <div class="flex items-center space-x-4">
                    <div class="w-16 h-16 bg-gradient-to-br from-red-500 to-red-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
                        AS
                    </div>
                    <div>
                        <h2 class="text-xl font-bold text-gray-800">Ahmad Syahrul</h2>
                        <p class="text-gray-600">Kontingen DKI Jakarta</p>
                    </div>
                </div>
                <div class="text-right">
                    <h1 class="text-2xl font-bold text-red-600">Dewasa Tunggal Putra</h1>
                    <p class="text-gray-600">Kategori Tanding</p>
                </div>
            </div>
        </div>

        <!-- Main Grid (3 columns) -->
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
            <!-- Wrong Move Card -->
            <div class="bg-red-500 rounded-xl shadow-md p-8 flex flex-col items-center justify-center min-h-64">
                <button id="wrongMoveBtn" class="text-white font-bold py-8 px-12 text-3xl transition-colors duration-200 w-full h-full">
                    <div class="text-6xl mb-4">✗</div>
                    Wrong Move
                </button>
            </div>

            <!-- Center Info Card -->
            <div class="bg-white rounded-xl shadow-md p-6">
                <div class="text-center mb-6">
                    <h3 class="text-3xl font-bold text-red-600 mb-2">Jurus ke: <span id="currentMove">1</span></h3>
                    <p class="text-xl text-red-500 font-semibold">Kesalahan: <span id="currentErrors">0</span> (Jurus ini)</p>
                </div>
                
                <div class="mb-4">
                    <h4 class="text-lg font-semibold text-gray-700 mb-3">Kemantapan / Penghayatan / Stamina</h4>
                    <div class="grid grid-cols-5 gap-2" id="scoreButtons">
                        <!-- Score buttons will be generated by JavaScript -->
                    </div>
                </div>
                
                <div class="text-center">
                    <p class="text-sm text-gray-600">Nilai Kategori: <span id="categoryScore" class="font-bold text-green-600">0.00</span></p>
                </div>
            </div>

            <!-- Next Move Card -->
            <div class="bg-green-500 rounded-xl shadow-md p-8 flex flex-col items-center justify-center min-h-64">
                <button id="nextMoveBtn" class="text-white font-bold py-8 px-12 text-3xl transition-colors duration-200 w-full h-full">
                    <div class="text-6xl mb-4">→</div>
                    Next Move
                </button>
            </div>
        </div>

        <!-- Bottom Grid (2 columns) -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Total Errors Card -->
            <div class="bg-white rounded-xl shadow-md p-6">
                <h3 class="text-xl font-semibold text-gray-700 mb-4">Total Kesalahan</h3>
                <div class="text-center">
                    <div class="text-5xl font-bold text-red-500" id="totalErrors">0</div>
                    <p class="text-gray-600 mt-2">Kesalahan dari semua jurus</p>
                </div>
            </div>

            <!-- Final Score Card -->
            <div class="bg-red-500 rounded-xl shadow-md p-6">
                <h3 class="text-xl font-semibold text-white mb-4 text-center">TOTAL NILAI AKHIR</h3>
                <div class="text-center">
                    <div class="text-6xl font-bold text-white" id="finalScore">9.90</div>
                    <p class="text-red-100 mt-2">Nilai Final</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Game state
        let currentMove = 1;
        let moveErrors = {}; // Track errors per move
        let totalCategoryScore = 0.00; // Category score (can be changed within moves 1-MAX_JURUS)
        const penaltyPerError = 0.01;
        const baseScore = 9.90;
        
        // Get dynamic values from controller
        const MAX_JURUS = parseInt(document.getElementById('max_jurus').value);
        const MATCH_TYPE = document.getElementById('match_type').value;
        const PERTANDINGAN_ID = parseInt(document.getElementById('pertandingan_id').value);
        const USER_ID = parseInt(document.getElementById('user_id').value);
        const CSRF_TOKEN = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

        // Initialize first move
        moveErrors[currentMove] = 0;

        // DOM elements
        const currentMoveEl = document.getElementById('currentMove');
        const currentErrorsEl = document.getElementById('currentErrors');
        const totalErrorsEl = document.getElementById('totalErrors');
        const finalScoreEl = document.getElementById('finalScore');
        const categoryScoreEl = document.getElementById('categoryScore');
        const wrongMoveBtn = document.getElementById('wrongMoveBtn');
        const nextMoveBtn = document.getElementById('nextMoveBtn');
        const scoreButtonsContainer = document.getElementById('scoreButtons');


        // Generate score buttons (0.01 - 0.10)
        function generateScoreButtons() {
            scoreButtonsContainer.innerHTML = '';
            
            // Show buttons if we're within allowed jurus limit
            if (currentMove <= MAX_JURUS) {
                for (let i = 1; i <= 10; i++) {
                    const score = (i * 0.01).toFixed(2);
                    const button = document.createElement('button');
                    
                    // Check if this score is currently selected
                    if (totalCategoryScore === parseFloat(score)) {
                        button.className = 'px-3 py-2 rounded-full text-sm font-medium transition-colors duration-200 bg-green-500 hover:bg-green-600 text-white';
                    } else {
                        button.className = 'px-3 py-2 rounded-full text-sm font-medium transition-colors duration-200 bg-gray-200 hover:bg-gray-300 text-gray-700';
                    }
                    
                    button.textContent = score;
                    button.onclick = () => selectScore(button, parseFloat(score));
                    scoreButtonsContainer.appendChild(button);
                }
            } else {
                // Show disabled message for moves beyond MAX_JURUS
                const message = document.createElement('div');
                message.className = 'text-center text-gray-500 italic py-4';
                message.textContent = `Nilai kategori hanya untuk jurus 1-${MAX_JURUS}`;
                scoreButtonsContainer.appendChild(message);
            }
        }

        // Select score button
        function selectScore(button, score) {
            // Only allow selection if we're within allowed jurus
            if (currentMove > MAX_JURUS) {
                return;
            }
            
            // Reset all buttons
            const buttons = scoreButtonsContainer.querySelectorAll('button');
            buttons.forEach(btn => {
                btn.className = 'px-3 py-2 rounded-full text-sm font-medium transition-colors duration-200 bg-gray-200 hover:bg-gray-300 text-gray-700';
            });
            
            // Highlight selected button
            button.className = 'px-3 py-2 rounded-full text-sm font-medium transition-colors duration-200 bg-green-500 hover:bg-green-600 text-white';
            
            // Update category score
            totalCategoryScore = score;
            categoryScoreEl.textContent = score.toFixed(2);
            
            // Send to database
            sendCategoryScore(score);
            
            updateDisplay();
        }

        // Calculate total errors
        function getTotalErrors() {
            return Object.values(moveErrors).reduce((sum, errors) => sum + errors, 0);
        }



        // Update displays
        function updateDisplay() {
            currentMoveEl.textContent = currentMove;
            currentErrorsEl.textContent = moveErrors[currentMove] || 0;
            
            const totalErrors = getTotalErrors();
            totalErrorsEl.textContent = totalErrors;
            
            const finalScore = Math.max(0, baseScore - (totalErrors * penaltyPerError) + totalCategoryScore);
            finalScoreEl.textContent = finalScore.toFixed(2);
        }

        // Send error to database
        function sendMoveError(jurusNumber) {
            fetch('/seni/tunggal-regu/add-error', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': CSRF_TOKEN
                },
                body: JSON.stringify({
                    pertandingan_id: PERTANDINGAN_ID,
                    user_id: USER_ID,
                    jurus_number: jurusNumber
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    console.log('Error saved:', data.data);
                } else {
                    console.error('Failed to save error:', data);
                }
            })
            .catch(error => console.error('Network error:', error));
        }

        // Send category score to database
        function sendCategoryScore(score) {
            fetch('/seni/tunggal-regu/set-category', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': CSRF_TOKEN
                },
                body: JSON.stringify({
                    pertandingan_id: PERTANDINGAN_ID,
                    user_id: USER_ID,
                    score: score,
                    current_jurus: currentMove
                })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    console.log('Category score saved:', data.data);
                } else {
                    console.error('Failed to save category score:', data);
                    alert(data.message || 'Gagal menyimpan category score');
                }
            })
            .catch(error => console.error('Network error:', error));
        }

        // Wrong move button handler
        wrongMoveBtn.addEventListener('click', () => {
            if (!moveErrors[currentMove]) {
                moveErrors[currentMove] = 0;
            }
            moveErrors[currentMove]++;
            
            // Send to database
            sendMoveError(currentMove);
            
            updateDisplay();
                
            // Add visual feedback
            wrongMoveBtn.classList.add('scale-95');
            setTimeout(() => wrongMoveBtn.classList.remove('scale-95'), 150);
        });

        // Next move button handler
        nextMoveBtn.addEventListener('click', () => {
            currentMove++;
            moveErrors[currentMove] = 0;
            updateDisplay();
            
            // Regenerate score buttons (will show disabled if beyond move 14)
            generateScoreButtons();
            
            // Keep showing the category score
            categoryScoreEl.textContent = totalCategoryScore.toFixed(2);
            
            // Add visual feedback
            nextMoveBtn.classList.add('scale-95');
            setTimeout(() => nextMoveBtn.classList.remove('scale-95'), 150);
        });

        // Initialize
        generateScoreButtons();
        updateDisplay();
    </script>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'97ac9dcc870e4112',t:'MTc1NzE0NzU1My4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>

